<?php
/**
 * @file Contains hook implementations and functions for this module.
 */

/**
 * Implements hook_menu().
 */
function forward_revisions_menu() {
  $items = [];

  $items['node/%node/revisions/%/activate'] = [
    'title' => 'Make a revision the current revision',
    'load arguments' => [3],
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['forward_revisions_activate_confirm', 1],
    'access callback' => '_node_revision_access',
    'access arguments' => [1, 'update'],
  ];
  $items['node/%node/publish'] = [
    'title' => 'Publish the node',
//    'load arguments' => [1],
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['forward_revisions_publish_confirm', 1],
    'access callback' => 'node_access',
    'access arguments' => ['update', 1],
  ];
  $items['node/%node/unpublish'] = [
    'title' => 'Unpublish the node',
//    'load arguments' => [1],
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['forward_revisions_unpublish_confirm', 1],
    'access callback' => 'node_access',
    'access arguments' => ['update', 1],
  ];
  $items['node/%node/revisions/%/new_revision'] = array(
    'title' => 'Create new revision',
    'load arguments' => [3],
    'page callback' => 'forward_revisions_new_revision',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'weight' => 0,
  );
  $items['node/%node/revisions/%/edit_revision'] = array(
    'title' => 'Edit revision',
    'load arguments' => [3],
    'page callback' => 'forward_revisions_edit_revision',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'weight' => 0,
  );
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function forward_revisions_menu_alter(&$items) {
  // Override node/%node/revisions.
  $items['node/%node/revisions']['page callback'] = 'forward_revisions_node_revisions_overview';
}

/**
 * Implements hook_admin_paths().
 */
function forward_revisions_admin_paths() {
  if (config_get('system.core', 'node_admin_theme')) {
    $paths = array(
      'node/*/revisions/*/activate' => TRUE,
      'node/*/publish' => TRUE,
      'node/*/unpublish' => TRUE,
      'node/*/revisions/*/new_revision' => TRUE,
      'node/*/revisions/*/edit_revision' => TRUE,
    );
    return $paths;
  }
  else {
    return array();
  }
}

/**
 * Provides a replacement for the node revisions page.
 */
function forward_revisions_node_revisions_overview(Node $node) {
  module_load_include('inc', 'node', 'node.pages');
  $build = node_revision_overview($node);

  $build['actions']= [
    '#type' => 'container',
    '#weight' => -1,
    'new_revision' => [
      '#type' => 'link',
      '#title' => 'Create new revision',
      '#href' => 'node/' . $node->nid . '/revisions/' . $node->vid . '/new_revision',
      '#attributes' => array('class' => 'button'),
    ],
  ];

  $node_type_name =  node_type_get_name($node);
  if ($node->status == NODE_PUBLISHED) {
    backdrop_set_message(t('This @node_type is published.', [
      '@node_type' => $node_type_name,
    ]), 'info');
    $build['actions']['unpublish'] = [
      '#type' => 'link',
      '#title' => 'Unpublish node',
      '#href' => 'node/' . $node->nid . '/unpublish',
      '#attributes' => array('class' => 'button'),
    ];
  }
  else {
    backdrop_set_message(t('This @node_type is not published.', [
      '@node_type' => $node_type_name,
    ]), 'warning');
    $build['actions']['publish'] = [
      '#type' => 'link',
      '#title' => 'publish node',
      '#href' => 'node/' . $node->nid . '/publish',
      '#attributes' => array('class' => 'button'),
    ];
  }

  $revision_list = node_revision_list($node);

  $key = 0;
  foreach ($revision_list as $vid => $revision) {

    $node_revision = entity_plus_revision_load('node', $vid);

    // Edit the action links.
    if ($vid != $node->vid) {
      // Remove the Revert option.
      unset($build['node_revisions_table']['#rows'][$key][1]['data']['#links']['revert']);

      array_splice($build['node_revisions_table']['#rows'][$key][1]['data']['#links'], 0, 0, [
        'new_draft' => [
          'title' => t('Edit Revision'),
          'href' => 'node/' . $node->nid . '/revisions/' . $vid . '/new_revision',
        ],
        'activate' => [
          'title' => t('Make current revision'),
          'href' => 'node/' . $node->nid . '/revisions/' . $vid . '/activate',
        ],
      ]);
    }

    $key++;
  }

  return $build;
}

/**
 * The confirmation form for activating a revision.
 */
function forward_revisions_activate_confirm($form, $form_state, $node_revision) {
  $form['#node_revision'] = $node_revision;
  return confirm_form($form, t('Are you sure you want to make the revision from %revision-date the current revision?', array(
    '%revision-date' => format_date($node_revision->revision_timestamp),
  )), 'node/' . $node_revision->nid . '/revisions', '', t('Save'), t('Cancel'));
}

/**
 * Form submission handler for forward_revisions_activate_confirm().
 */
function forward_revisions_activate_confirm_submit($form, &$form_state) {
  $node_revision = $form['#node_revision'];

  $node_revision->setIsActiveRevision();
  $node_revision->save();

  backdrop_set_message(t('@type %title has been set as the active revision.', array(
    '@type' => node_type_get_name($node_revision),
    '%title' => $node_revision->title,
  )));
  $form_state['redirect'] = 'node/' . $node_revision->nid . '/revisions';
}

/**
 * The confirmation form for publishing a draft revision.
 */
function forward_revisions_publish_confirm($form, $form_state, $node) {
  $form['#node'] = $node;
  return confirm_form($form, t('Are you sure you want to publish %node_title?', array(
    '%node_title' => $node->title,
  )), 'node/' . $node->nid . '/revisions', '', t('Publish'), t('Cancel'));
}

/**
 * Form submission handler for forward_revisions_publish_confirm().
 */
function forward_revisions_publish_confirm_submit($form, &$form_state) {
  $node = $form['#node'];

  $node->status = NODE_PUBLISHED;
  $node->save();

  db_update('node_revision')
    ->fields(['status' => $node->status])
    ->condition('nid', $node->nid)
    ->execute();

  backdrop_set_message(t('@type %title has been published.', array(
    '@type' => node_type_get_name($node),
    '%title' => $node->title,
  )));
  $form_state['redirect'] = 'node/' . $node->nid . '/revisions';
}

/**
 * The confirmation form for publishing a draft revision.
 */
function forward_revisions_unpublish_confirm($form, $form_state, $node) {
  $form['#node'] = $node;
  return confirm_form($form, t('Are you sure you want to unpublish %node_title?', array(
    '%node_title' => $node->title,
  )), 'node/' . $node->nid . '/revisions', '', t('Unpublish'), t('Cancel'));
}

/**
 * Form submission handler for forward_revisions_publish_confirm().
 */
function forward_revisions_unpublish_confirm_submit($form, &$form_state) {
  $node = $form['#node'];

  $node->status = NODE_NOT_PUBLISHED;
  $node->save();

  db_update('node_revision')
    ->fields(['status' => $node->status])
    ->condition('nid', $node->nid)
    ->execute();

  backdrop_set_message(t('@type %title has been unpublished.', array(
    '@type' => node_type_get_name($node),
    '%title' => $node->title,
  )));
  $form_state['redirect'] = 'node/' . $node->nid . '/revisions';
}

/**
 * Loads the node form for creating a new revision.
 */
function forward_revisions_new_revision(Node $node) {
  module_load_include('inc', 'node', 'node.pages');

  $type_name = node_type_get_name($node);
  backdrop_set_title(t('New revision of @type %title', array(
    '@type' => $type_name,
    '%title' => $node->title,
  )), PASS_THROUGH);

  $form = backdrop_get_form($node->type . '_node_form', $node);
  return $form;
}

/**
 * Submit handler for the new revision form.
 */
function forward_revisions_new_revision_submit($form, &$form_state) {
//  dpm($form);
//  dpm($form_state);
}

/**
 * Loads the node form for editing an existing revision.
 */
function forward_revisions_edit_draft(Node $node) {
  module_load_include('inc', 'node', 'node.pages');

  $type_name = node_type_get_name($node);
  backdrop_set_title(t('Edit draft of @type %title', array(
    '@type' => $type_name,
    '%title' => $node->title,
  )), PASS_THROUGH);

  $form = backdrop_get_form($node->type . '_node_form', $node);
  return $form;
}

/**
 * Submit handler for the edit draft form.
 */
function forward_revisions_edit_draft_submit($form, &$form_state) {}

/**
 * Implements hook_form_alter().
 */
function forward_revisions_form_alter(&$form, &$form_state, $form_id) {
//  dpm($form);
//  dpm($form_state);
//  dpm($form_id);

  $args = arg();

  $node_form_string = '_node_form';
  if (substr_compare($form_id, $node_form_string, -strlen($node_form_string)) === 0) {

    // Add save new draft button.
//    array_splice($form['actions'], 1, 0, [
//      'new_revision' => [
//        '#type' => 'submit',
//        '#access' => TRUE,
//        '#value' => t('New revision'),
//        '#weight' => 6,
//        '#submit' => [
//          'forward_revisions_new_revision_submit',
//          'node_form_submit'
//        ],
//      ]
//    ]);
//    $form['actions']

    if (!empty($args[4])) {
      if ($args[4] == 'edit_revision') {

      }
      else if ($args[4] == 'new_revision') {
        // Force new revision on.
      }
    }

    //    $form['actions']['new_draft'] = [
//      '#type' => 'submit',
//      '#access' => TRUE,
//      '#value' => t('New draft'),
//      '#weight' => 4,
//      '#submit' => ['forward_revisions_new_draft_submit'],
//    ];
  }
}
